from flask import Flask, render_template, request
import random

app = Flask(__name__)

# Sample data: Replace this with your actual data
people_data = {
    1: "Collin Madziwo",
    2: "Maycock Hore",
    3: "Vacant",
    4: "Vivian Hansen",
    5: "Angula onesmus",
    6: "Salom Katangolo",
    7: "Rustika Shaanika",
    8: "Helvi Amunyela",
    9: "Josef Amunyela",
    10: "Dorothy Hangara",
    11: "Martha Simeon",
    12: "Ester Shinyenga",
    13: "Carmen Du Plessis",
    14: "Nyanyukweni Shikoyeni",
    15: "Laureta Chipejo",
    16: "Ndinelao Shipilika",
    17: "Aune E. zimmer",
    18: "Daria Kapofi",
    19: "Eradius Lazarus",
    20: "Victoria Amushila",
    21: "Nestor Shekunangela",
    22: "Michael Orisamolade",
    23: "martin Ndume",
    24: "Deon kela",
    25: "Sakaria Nebwaya",
    26: "Rachael Shiwayu",
    27: "Emilia Frans",
    28: "Lukas Tobias",
    29: "Aina hamutenya",
    30: "Martin Haufiku",
    31: "Ndeshipanda Kashihakumwa",
    32: "Paulo Vicente",
    33: "Suttela Sam",
    34: "James Taukondjele",
    35: "Immelda Tlhalehile",
    36: "Mirjam Endjala",
    37: "Maria Kamati",
    38: "Gace Bauleth",
    39: "Tuulikefo Shingulu",
    40: "Martha Ndakolo",
    41: "Esther Andreas",
    42: "Magano Petrus",
    43: "Susana Endjala",
    44: "Lukas Hamutenya",
    45: "Simeon Ndishishi",
    46: "Simeon Amupolo",
    47: "Johnna Nangolo",
    48: "Hendelina Kalimba",
    49: "Festus Frans",
    50: "David Shindinge",
    51: "katrina Natanael",
    52: "Abraham Frans",
    53: "Jason Iiyambo",
    54: "Udyombala Simson",
    55: "Victor Henock",
    56: "Heimo Udjombala",
    57: "Ananias Shikongo",
    58: "kanyemba Andreas",
    59: "David /Gameb",
    60: "Fillemon Nakashole",
    61: "Dhimbulukweni Lukas",
    62: "Roger Matias",
    63: "Soskar Kanghono",
    64: "karunga Masoya",
    65: "Peter Hamusira",
    66: "Kaino Shikonga",
    67: "Petrus Puleni",
    68: "Thandekile Phulu",
    69: "Akinyemi Moshood",
    70: "Helena Ekandjo",
    71: "Elizabeth Veiko",
    72: "Anna-Lisa Shoopala",
    73: "Kunguana Muatjitjeja",
    74: "Dr Custon Ziwon",
    75: "Nelao Heita",
    76: "Rebbeca Halweendo",
    77: "Dr Leonard Onjefu",
    78: "Willardson Kubanga",
    79: "Stanley Mapanda",
    80: "Tapera Macheka",
    81: "Olivia Shilongo",
    82: "Abiner Haikiyata",
    83: "Cliff Mbala",
    84: "Chaibva Rumbidzai",
    85: "Isak Gabriel",
    86: "Sakaria Nendongo",
    87: "Ernest Zemburuka",
    88: "Simataa Chinduka",
    89: "Jesse Jose",
    90: "Limbo Lishoni",
    91: "Abel Simuketa",
    92: "Victoria Lazarus",
    93: "Lukas Kamenye",
    94: "Salmi Angula",
    95: "Selma Ingo",
    96: "Immanuel Shatepa",
    97: "Blessed Mateta",
    98: "Joseph",
    99: "Leevi Ndongo",
    100: "Selma Usebiu",
    101: "Maxwell Muyambo",
    102: "Frances M Nunuhe",
    103: "Timba Ayoub William",
    104: "Tautiko Mungandjera",
    105: "Johannes Naingwedje",
    106: "Dr Gift Kavari",
    107: "Cisiliya Mbango",
    108: "Vinolia Khembo",
    109: "Micheal Shilombode",
    110: "Helvi Shilomboleni",
    111: "Josephina Gerhard",
    112: "Tsombo Tshitukenina",
    113: "Dr John Njue",
    114: "Dumeni Petrus",
    115: "Mclean Ephata Uwuses",
    116: "Prof Lischen Hoases-Gorases",
    117: "Favour Ehwariene",
    118: "Solomon Abegunde",
    119: "Lazarus Shimanda",
    120: "Professor Alfred Kamupingene",
    121: "Haidula Petrina",
    122: "Evagelista Endunde",
    123: "Tangeni Usiku",
    124: "Anna Kaoiya",
    125: "Mathew Haikali",
    126: "Isack Hamata",
    127: "Mukai Nyangara",
    128: "Amalia Kauna Matheus",
    129: "Dr Mpingana Akawa",
    130: "Grace Kahuikee",
    131: "Havelinus Shemuketa",
    132: "Victory Kashava",
    133: "Eden-Ezer Kalola",
    134: "Andre Kandundu",
    135: "Moses Mbeeli",
    136: "Yvonne Oxurus",
    137: "Ester Kiangi",
    138: "Ester Josua",
    139: "Uzera Isack",
    140: "Wilfred Mbamba",
    141: "Sydney Mutelo",
    142: "Shivute Immanule",
    143: "Julia Pelestrelo",
    144: "Inheri Shaanika",
    145: "Martin Kandjware",
    146: "Hilaria N Mungongolo",
    147: "Wilka Erasmus",
    148: "Frietz Namupala",
    149: "Agnes Mwanza",
    150: "Ericka K Shivute",
    151: "Alisa Johannes",
    152: "Beatha N Amukwaya",
    153: "Elina N Thomas",
    154: "Erick P Kaishungu",
    155: "Emilia Hosea",
    156: "Helvi Shimpanda",
    157: "Epifania Tomas",
    158: "Lydia Kasheshe",
    159: "Dnaiel Mwetupanga",
    160: "Jesaya Lumbu",
    161: "Bacilia Martin",
    162: "Maria Kamhulu",
    163: "Sharon Mkhize",
    164: "Eveline Musirika",
    165: "Lenie Gerirses",
    166: "Stefanus Fillipus",
    167: "Nikanol Klaudia",
    168: "Nekanol Sakaria",
    169: "Jennifer Gottfried",
    170: "Alvina Hailonga",
    171: "Liyalo Shipulwa",
    172: "Onemus Johannes",
    173: "Wilbur Van Shcalkwyk",
    174: "Gervasius Hango",
    175: "Ednauso Quindembe",
    176: "Julia Mokhatu",
    177: "Fillemon Thomas",
    178: "Bianca Nhund",
    179: "Elizabeth Kanyama",
    180: "Neumann Punaete",
    181: "Moses Hilde",
    182: "Mingana Nekwaya",
    183: "David Joshua",
    184: "Njubei Sandra",
    185: "Werner Mechtilde",
    186: "Nuuyoma Aktofel",
    187: "Jao Pedro",
    188: "Kaimbi Marcellina",
    189: "Hensen Bradley",
    190: "Aiata Elia",
    191: "Raina Nehale",
    192: "Albertina Mwaamenage", 
    193: "Filomina Shikesho",
    194: "Natalia Andreas",
    195: "Patrck Mukunisha",
    196: "Absalom Frans",
    197: "Selma Lipinge",
    198: "Bella Judite Louis",
    199: "Selma STT Nangolo",
    200: "Lee- Ann Richter",
    201: "Josef Fillippus Natangwe",
    202: "Mutilifa Charles",
    203: "Joseph David",

    # Add more unique numbers and names
}

# Initialize the set of available numbers
available_numbers = set(people_data.keys())

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/pair', methods=['POST'])
def pair():
    user_number = int(request.form.get('user_number'))

    if user_number in available_numbers:
        available_numbers.remove(user_number)
        paired_number = random.choice(list(available_numbers))
        available_numbers.remove(paired_number)
        paired_name = people_data[paired_number]
        message = f"You are paired with {paired_name}"
    else:
        message = "Invalid number. Please enter a valid and available number."

    return render_template('result.html', message=message)

if __name__ == '__main__':
    app.run(debug=True)
